### ISSUE TITLE
[vite]: Rollup failed to resolve import

### ISSUE THREAD

**Issue by pashagolub** [ananthakumaran/paisa#79]
Trying to build binaries against master getting this error:

```
$ npm run build && go build

> paisa@0.0.1 build
> vite build


vite v4.4.8 building SSR bundle for production...
✓ 223 modules transformed.
✓ built in 15.20s
[vite]: Rollup failed to resolve import "@datasert/cronjs-parser" from "C:/Users/pasha/Code/paisa/src/lib/transaction_sequence.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
error during build:
Error: [vite]: Rollup failed to resolve import "@datasert/cronjs-parser" from "C:/Users/pasha/Code/paisa/src/lib/transaction_sequence.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file:///C:/Users/pasha/Code/paisa/node_modules/vite/dist/node/chunks/dep-75f53616.js:48093:27)
    at onRollupWarning (file:///C:/Users/pasha/Code/paisa/node_modules/vite/dist/node/chunks/dep-75f53616.js:48125:9)
    at onwarn (file:///C:/Users/pasha/Code/paisa/node_modules/vite/dist/node/chunks/dep-75f53616.js:47853:13)
    at file:///C:/Users/pasha/Code/paisa/node_modules/rollup/dist/es/shared/node-entry.js:24194:13
    at Object.logger [as onLog] (file:///C:/Users/pasha/Code/paisa/node_modules/rollup/dist/es/shared/node-entry.js:25867:9)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/pasha/Code/paisa/node_modules/rollup/dist/es/shared/node-entry.js:24780:26)
    at file:///C:/Users/pasha/Code/paisa/node_modules/rollup/dist/es/shared/node-entry.js:24740:26
```

**Comment by ananthakumaran** [comment]
try `$ npm install && npm run build && go build`

**Comment by pashagolub** [comment]
Thanks. My bad. Never worked with npm before.
